package: iam
generate:
  echo-server: true
  models: true
  strict-server: true
output-options:
  skip-prune: false
  exclude-schemas:
    - DIDDocument
    - OAuthAuthorizationServerMetadata
    - OAuthClientMetadata
    - PresentationDefinition
    - ErrorResponse
    - TokenResponse
