package: iam
generate:
  echo-server: true
  client: true
  models: true
  strict-server: true
output-options:
  skip-prune: false
  exclude-schemas:
    - DIDDocument
    - OAuthAuthorizationServerMetadata
    - OAuthClientMetadata
    - PresentationDefinition
    - PresentationSubmission
    - RedirectResponse
    - TokenResponse
    - VerifiablePresentation
    - VerifiableCredential
    - WalletOwnerType
    - ErrorResponse
