package: client
generate:
  echo-server: false
  client: true
  models: true
  strict-server: true
output-options:
  skip-prune: true
  exclude-schemas:
  - PEXPolicy
  - PresentationDefinition
  - PresentationSubmission
  - AuthorizedRequest
