services:
  nodeA-backend:
    image: "${IMAGE_NODE_A:-nutsfoundation/nuts-node:master}"
    ports:
      - "18081:8081"
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    volumes:
      - "./node-A/nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "./node-A/data:/opt/nuts/data:rw"
      - "../../tls-certs/nodeA-certificate.pem:/opt/nuts/certificate-and-key.pem:ro"
      - "../../tls-certs/truststore.pem:/opt/nuts/truststore.pem:ro"
      # did:web resolver uses the OS CA bundle, but e2e tests use a self-signed CA which can be found in truststore.pem
      # So we need to mount that file to the OS CA bundle location, otherwise did:web resolving will fail due to untrusted certs.
      - "../../tls-certs/truststore.pem:/etc/ssl/certs/Nuts_RootCA.pem:ro"
      - "../../tls-certs/truststore.pem:/etc/ssl/certs/truststore.pem:ro"
      - "./node-A/presentationexchangemapping.json:/opt/nuts/policies/presentationexchangemapping.json:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often
  nodeB-backend:
    image: "${IMAGE_NODE_B:-nutsfoundation/nuts-node:master}"
    ports:
      - "28081:8081"
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    volumes:
      - "./node-B/data:/opt/nuts/data:rw"
      - "./node-B/nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "../../tls-certs/nodeB-certificate.pem:/opt/nuts/certificate-and-key.pem:ro"
      - "../../tls-certs/truststore.pem:/opt/nuts/truststore.pem:ro"
      # did:web resolver uses the OS CA bundle, but e2e tests use a self-signed CA which can be found in truststore.pem
      # So we need to mount that file to the OS CA bundle location, otherwise did:web resolving will fail due to untrusted certs.
      - "../../tls-certs/truststore.pem:/etc/ssl/certs/Nuts_RootCA.pem:ro"
      - "../../tls-certs/truststore.pem:/etc/ssl/certs/truststore.pem:ro"
      - "./node-B/presentationexchangemapping.json:/opt/nuts/policies/presentationexchangemapping.json:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often
  nodeA:
    image: nginx:1.25.1
    volumes:
      - "../../shared_config/nodeA-http-nginx.conf:/etc/nginx/conf.d/nuts-http.conf:ro"
      - "../../tls-certs/nodeA-certificate.pem:/etc/nginx/ssl/server.pem:ro"
      - "../../tls-certs/nodeA-certificate.pem:/etc/nginx/ssl/key.pem:ro"
      - "../../tls-certs/truststore.pem:/etc/nginx/ssl/truststore.pem:ro"
    ports:
      - "10443:443"
  nodeB:
    image: nginx:1.25.1
    volumes:
      - "../../shared_config/nodeB-http-nginx.conf:/etc/nginx/conf.d/nuts-http.conf:ro"
      - "../../tls-certs/nodeB-certificate.pem:/etc/nginx/ssl/server.pem:ro"
      - "../../tls-certs/nodeB-certificate.pem:/etc/nginx/ssl/key.pem:ro"
      - "../../tls-certs/truststore.pem:/etc/nginx/ssl/truststore.pem:ro"
    ports:
      - "20443:443"
  resource:
    image: nginx:1.25.1
    volumes:
      - "./resource/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../scripts/oauth2.js:/etc/nginx/oauth2.js:ro"
    depends_on:
      - nodeA-backend
