services:
  nutsnode:
    image: "${IMAGE_NODE_A:-nutsfoundation/nuts-node:lspxnuts}"
    pull_policy: always
    ports:
      - "18081:8081"
    environment:
      NUTS_STRICTMODE: false
    #volumes:
    #  - "./definitions/:/opt/nuts/definitions:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often