concept: authorization
credentialType: NutsAuthorizationCredential
indices:
  - name: index_id
    parts:
      - path: id
  - name: index_issuer
    parts:
      - path: issuer
  - name: index_holder
    parts:
      - path: credentialSubject.id
      - path: credentialSubject.purposeOfUse
      - path: credentialSubject.resource.#.path
        transformer: lowercase
  - name: index_subject
    parts:
      - path: credentialSubject.id
      - path: credentialSubject.subject
